#!/usr/bin/env python3
"""Build the committed black-and-white ORRERY portrait sets."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path

from PIL import Image, ImageOps


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = Path(
    os.environ.get("ORRERY_PORTRAIT_SOURCE_DIR", REPO_ROOT / "assets" / "portraits_src")
)
OUTPUT_DIR = REPO_ROOT / "assets" / "portraits"
OUTPUT_DIR_64 = REPO_ROOT / "assets" / "portraits_64"
MANIFEST_PATH = SOURCE_DIR / "manifest.json"
CREDITS_PATH = REPO_ROOT / "CREDITS.md"
SOURCE_SUFFIXES = {".jpg", ".jpeg", ".png"}
PORTRAIT_TOP_ANCHOR = 0.12
REQUIRED_MANIFEST_FIELDS = (
    "url",
    "sha1",
    "revision_id",
    "license",
    "artist",
    "credit",
    "downloaded_at",
    "source_file",
)

# Per-stem crop boxes (left, top, right, bottom) in source-pixel coordinates,
# for engravings whose decorative frame would otherwise dominate the generic
# square crop. Boxes should be square and frame the head down to the chest.
CROP_OVERRIDES: dict[str, tuple[int, int, int, int]] = {
    "Guericke": (492, 744, 1476, 1728),
    # Los Alamos ID badge: stop above the badge number printed under the photo.
    "Feynman": (28, 12, 468, 452),
    # Book frontispiece: stop above the printed signature under the photograph.
    "Bose": (60, 24, 1160, 1124),
    # Group photograph of the Ratio Club: Turing, seated at the front left.
    "Turing": (680, 1660, 1280, 2260),
}


def source_files(source_dir: Path) -> list[Path]:
    return sorted(
        (
            path
            for path in source_dir.iterdir()
            if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES
        ),
        key=lambda path: (path.stem.casefold(), path.name.casefold()),
    )


def sha1(path: Path) -> str:
    digest = hashlib.sha1()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_manifest(sources: list[Path]) -> dict[str, dict[str, object]]:
    """Load and strictly validate provenance before processing any portrait."""
    if not MANIFEST_PATH.is_file():
        raise SystemExit(f"portrait manifest does not exist: {MANIFEST_PATH}")
    try:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise SystemExit(f"invalid portrait manifest: {error}") from error
    if not isinstance(manifest, dict):
        raise SystemExit("portrait manifest must be a JSON object keyed by portrait stem")

    stems = {source.stem for source in sources}
    if set(manifest) != stems:
        missing = sorted(stems - set(manifest))
        extra = sorted(set(manifest) - stems)
        raise SystemExit(f"portrait manifest/source mismatch: missing={missing}, extra={extra}")

    for source in sources:
        entry = manifest[source.stem]
        if not isinstance(entry, dict):
            raise SystemExit(f"manifest entry must be an object: {source.stem}")
        absent = [field for field in REQUIRED_MANIFEST_FIELDS if not entry.get(field)]
        if absent:
            raise SystemExit(f"manifest entry missing {absent}: {source.stem}")
        if entry["source_file"] != source.name:
            raise SystemExit(f"manifest source_file mismatch: {source.stem}")
        if not str(entry["url"]).startswith("https://"):
            raise SystemExit(f"manifest URL must use HTTPS: {source.stem}")
        actual_sha1 = sha1(source)
        if entry["sha1"] != actual_sha1:
            raise SystemExit(
                f"manifest SHA-1 mismatch for {source.name}: "
                f"expected {entry['sha1']}, got {actual_sha1}"
            )
    return manifest


def write_credits(manifest: dict[str, dict[str, object]]) -> None:
    """Generate a distribution-ready attribution record from the provenance manifest."""
    lines = [
        "# Portrait credits",
        "",
        "Generated by `scripts/build_portraits.py`; do not edit manually.",
        "Each listed output is cropped, grayscale-converted, auto-contrasted, and resized from its source.",
        "",
    ]
    for stem in sorted(manifest, key=str.casefold):
        entry = manifest[stem]
        lines.extend(
            [
                f"## {stem}",
                "",
                f"- Source: {entry['url']}",
                f"- Source revision: {entry['revision_id']}",
                f"- Source SHA-1: `{entry['sha1']}`",
                f"- License: {entry['license']}"
                + (f" ({entry['license_url']})" if entry.get("license_url") else ""),
                f"- Artist: {entry['artist']}",
                f"- Credit: {entry['credit']}",
                "- Changes: crop; grayscale; autocontrast; resize to 256 px and 64 px PNG.",
                "",
            ]
        )
    lines.extend(
        [
            "## Pixel-art portraits",
            "",
            "The pixel-art portraits under `assets/portraits_px/` were generated by the author (gyroid)",
            "with ChatGPT image generation from text prompts only; no photographs were used as input.",
            "They are distributed under the same terms as the repository (see `LICENSE`).",
            "",
            "## Provider logos",
            "",
            "The usage pill names Claude and Codex (OpenAI) by their logos, taken from Iconify.",
            "The same files ship in orrery-telemetry as `dashboard/assets/`.",
            "",
            "| File | Mark | Source | License |",
            "| --- | --- | --- | --- |",
            "| `bridge/assets/anthropic.svg` | Claude | Simple Icons (Iconify `simple-icons:claude`) | CC0 1.0 |",
            "| `bridge/assets/openai.svg` | OpenAI | SVG Logos by Gil Barbara (Iconify `logos:openai-icon`) | CC0 1.0 |",
            "",
            "Changes: fill colour set to `#ece2cc`.",
            "Each logo is a trademark of its company and is used only to identify the provider.",
            "",
        ]
    )
    CREDITS_PATH.write_text("\n".join(lines), encoding="utf-8")


def square_crop(image: Image.Image) -> Image.Image:
    """Crop to a square, keeping portrait-oriented faces near the top."""
    width, height = image.size
    if height > width:
        top = round((height - width) * PORTRAIT_TOP_ANCHOR)
        return image.crop((0, top, width, top + width))
    if width > height:
        left = (width - height) // 2
        return image.crop((left, 0, left + height, height))
    return image.copy()


def build_one(source: Path, output_256: Path, output_64: Path) -> None:
    with Image.open(source) as opened:
        transposed = ImageOps.exif_transpose(opened)
        override = CROP_OVERRIDES.get(source.stem)
        cropped = transposed.crop(override) if override else square_crop(transposed)
        grayscale = ImageOps.grayscale(cropped)
        contrasted = ImageOps.autocontrast(grayscale, cutoff=1)
        portrait_256 = contrasted.resize((256, 256), Image.Resampling.LANCZOS)
        portrait_64 = contrasted.resize((64, 64), Image.Resampling.LANCZOS)
        portrait_256.save(output_256, format="PNG", optimize=True)
        portrait_64.save(output_64, format="PNG", optimize=True)


def outputs_are_current(source: Path, *outputs: Path) -> bool:
    source_mtime = source.stat().st_mtime_ns
    return all(
        output.is_file() and output.stat().st_mtime_ns >= source_mtime
        for output in outputs
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="rebuild portraits even when both outputs are up to date",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not SOURCE_DIR.is_dir():
        raise SystemExit(f"portrait source directory does not exist: {SOURCE_DIR}")

    sources = source_files(SOURCE_DIR)
    if not sources:
        raise SystemExit(f"no jpg/jpeg/png portraits found in: {SOURCE_DIR}")
    manifest = load_manifest(sources)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR_64.mkdir(parents=True, exist_ok=True)

    built = 0
    skipped = 0
    for source in sources:
        output_256 = OUTPUT_DIR / f"{source.stem}.png"
        output_64 = OUTPUT_DIR_64 / f"{source.stem}.png"
        if not args.force and outputs_are_current(source, output_256, output_64):
            skipped += 1
            continue
        build_one(source, output_256, output_64)
        built += 1

    write_credits(manifest)
    print(f"portraits: {len(sources)} source(s), {built} built, {skipped} skipped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
